export const INIT_FETCH_TODO_LIST = 'INIT_FETCH_TODO_LIST';
export const INIT_CREATE_TODO = 'INIT_CREATE_TODO';
export const INIT_UPDATE_TODO = 'INIT_UPDATE_TODO';
export const INIT_DELETE_TODO = 'INIT_DELETE_TODO';